#pragma once  // GENERATED by tools/binding_gen.py from tools/binding_schema.py — do not hand-edit
// ═══════════════════════════════════════════════════════════════════════
// THE BINDING REGISTRY (C6, recut by LOOM_2) — the single source of
// truth for GPU binding NUMBERS. Governed by L6 and L22,
// docs/LAWS.md; the numbers are the schema's
// (tools/binding_schema.py) and this file is GENERATED from it.
//
// The shape of the table: numbers are GROUP-SCOPED (g0..g3 are the
// four strata of the LOOM_2 recut — WORLD, FRAME, FAMILY-STATE,
// FAMILY-TEXTURES), and ONE CONSTANT PER SLOT; a slot may carry
// several declarations (the fc_ cull aliases). The MESHGEN
// convergence CONVERGED and then EMPTIED: five kernels shared three
// numbers so four families could ride one layout, PRUNE_2 excised
// four, and ONE_WORLD-I U3 took the arch — the trio's last
// occupant. Slots 180/181/182 are unallocated now, not reserved.
//
// The WGSL @binding literals in world.wgsl (55 declarations over 52 slots;
// aliases: fc_config, fc_patches, fc_vp)
// are a MIRROR of this file, kept in lockstep by boot-time
// validation and by binding_gen.py --check. The render = compute
// + 200 witness band is RETIRED — its epitaph closes this file.
// ═══════════════════════════════════════════════════════════════════════
#include <cstdint>

namespace t7 {
    namespace the_board {
        namespace bind {

            // ─────────────────────────────────────────────────────────────
            // GROUP 0 — WORLD (LOOM_2 recut, stratum 0).
            // ─────────────────────────────────────────────────────────────
            namespace g0 {
                // WORLD — R1: the two module-wide design tables every family reads.
                inline constexpr uint32_t config                      = 0;  // aka fc_config
                inline constexpr uint32_t tile_grid                   = 1;
            } // namespace g0

            // ─────────────────────────────────────────────────────────────
            // GROUP 1 — FRAME (stratum 1).
            // ─────────────────────────────────────────────────────────────
            namespace g1 {
                // FRAME — R2 v2: the per-frame ro faces, the light system and the two shared samplers.
                inline constexpr uint32_t signal                      = 0;
                inline constexpr uint32_t frame_r                     = 1;  // FrameR — CHORD_3: lighting + vp + camera, one uniform block per frame; vp and camera arrive by encoder copy from the GPU-sovereign homes (g2:240 vp_data, g2:241 camera_state), never by readback
                inline constexpr uint32_t bilinear_sampler            = 5;
                inline constexpr uint32_t nearest_sampler             = 6;
            } // namespace g1

            // ─────────────────────────────────────────────────────────────
            // GROUP 2 — FAMILY-STATE (stratum 2): buffer seats, banded
            // per family in roster order, band width 20.
            // ─────────────────────────────────────────────────────────────
            namespace g2 {
                // AGENTS (0–19)
                inline constexpr uint32_t agent_state                 = 0;
                inline constexpr uint32_t agent_room                  = 1;  // AgentRoomConstants — CHORD_1: portals + behaviors + tier_gains + occupier_amg, one uniform block at world cadence (2864 B)
                inline constexpr uint32_t floating_entities           = 2;
                inline constexpr uint32_t render_agents               = 5;
                inline constexpr uint32_t render_floating             = 6;
                inline constexpr uint32_t field_bus                   = 9;  // FieldBus — CHORD_2: ribbon + authored, one uniform block at frame cadence (256 B; RIBBON_1 took the ring poses out — the field reads the body through g2:145)
                inline constexpr uint32_t field_forces                = 10;  // vec4<f32>[FIELD_SUBSCRIBER_CAP] — read_write, the field's one output

                // AURA (20–39)
                inline constexpr uint32_t pawn_aura_cfg               = 20;
                inline constexpr uint32_t pawn_aura_cells             = 21;

                // PATCHGEN (40–59)
                // F1, ratified: a home is a numbering band, not
                // necessarily a seat. The heightfield ESTATE — write
                // faces, read faces, the CPU grid that indexes it, the
                // sampler that reads it — bands under the family that
                // AUTHORS the estate; readers borrow at its numbers.
                // R3a extended from resource to estate.
                inline constexpr uint32_t patch_params_batch          = 40;  // array<PatchParams> — the frame's batch, indexed by workgroup_id.z (LATTICE_1)
                inline constexpr uint32_t pyramid_instances           = 42;
                inline constexpr uint32_t patch_grid                  = 43;

                // CULL (60–79)
                inline constexpr uint32_t fc_draw_plan                = 60;  // ECONOMY_1 draw plan: counts + zone rects (uniform, cull kernel only). Reuses the slot the retired terrain_mesh_indices freed — L6 item 5, the cmg precedent.
                inline constexpr uint32_t patch_instances             = 61;  // aka fc_patches — aka fc_patches
                inline constexpr uint32_t fc_visible                  = 63;
                inline constexpr uint32_t fc_indirect                 = 64;

                // AUTOMATON (100–119)
                inline constexpr uint32_t auto_config                 = 101;
                inline constexpr uint32_t auto_life                   = 102;

                // ORBS (120–139)
                inline constexpr uint32_t orb_state                   = 120;
                inline constexpr uint32_t orb_config                  = 121;
                inline constexpr uint32_t orb_state_prev              = 122;
                inline constexpr uint32_t orb_state_ro                = 123;
                inline constexpr uint32_t orb_state_prev_rw           = 124;

                // RIBBON (140–159)
                inline constexpr uint32_t ribbon_state                = 140;
                inline constexpr uint32_t ring_xforms                 = 141;
                inline constexpr uint32_t ribbon_spine                = 142;  // the chord ring — one vec4 per cube_size of flight; ring k reads slot head−k
                inline constexpr uint32_t render_ring_xforms          = 143;
                inline constexpr uint32_t ribbon_body_rw              = 144;  // RibbonBody — head + saddle + emit + deform; the ribbon room writes
                inline constexpr uint32_t ribbon_body_read            = 145;  // the agents' room's read of the same home: the mount reads .saddle, the field reads .emit

                // SCENE (200–219)
                inline constexpr uint32_t scene_constants             = 200;  // SceneConstants — CHORD_4: tier_gains + figure_profiles + ribbon, one uniform block at world cadence (4336 B, render VS only; bound by the scene AND shadow layouts)

                // FRAME_K (240–259)
                inline constexpr uint32_t vp_data                     = 240;  // aka fc_vp (frustum-cull alias) — aka fc_vp
                inline constexpr uint32_t camera_state                = 241;
            } // namespace g2

            // ─────────────────────────────────────────────────────────────
            // GROUP 3 — FAMILY-TEXTURES (stratum 3): texture, sampler
            // and storage-texture seats, same family bands.
            // ─────────────────────────────────────────────────────────────
            namespace g3 {
                // AURA (20–39)
                inline constexpr uint32_t pawn_aura_tex_write         = 20;
                inline constexpr uint32_t pawn_aura_read              = 21;

                // PATCHGEN (40–59)
                inline constexpr uint32_t patch_heightfield_array_write = 40;
                inline constexpr uint32_t patch_cell_color_array_write = 41;
                inline constexpr uint32_t photo_heightfield           = 42;
                inline constexpr uint32_t photo_sampler               = 43;
                inline constexpr uint32_t patch_heightfield_array_read = 44;
                inline constexpr uint32_t patch_cell_color_array_read = 45;

                // AUTOMATON (100–119)
                inline constexpr uint32_t live_card_write             = 100;  // GROUND_CARD_1: the live card (storage-tex write; writer kernel)
                inline constexpr uint32_t auto_life_tex_write         = 101;
                inline constexpr uint32_t auto_life_read              = 102;
                inline constexpr uint32_t live_card_read              = 103;  // GROUND_CARD_1: the live card (sampled read; render + compute)

                // SCENE (200–219)
                inline constexpr uint32_t shadow_map                  = 200;
                inline constexpr uint32_t shadow_sampler              = 201;
            } // namespace g3

            // ──────────────────────────────────────────────────────────────
            // EPITAPH — the render = compute + 200 band (C6 → LOOM_2).
            // From C6 until the recut, four static_asserts held the render
            // mirrors exactly 200 above their compute twins; they were the
            // witness over the authored literals, never their source. The
            // recut retires the numbering they checked, so they die with it
            // (P-inv, RECUT_PLAN v2). Their successors are the schema and
            // binding_gen.py --check, which verify every number in every
            // mirror, both directions, at every recon gate.
            // ──────────────────────────────────────────────────────────────
            // ──────────────────────────────────────────────────────────────
            // L23-PRIME — THE SCOPE LAW (A8, superseding A7 L23). Within one
            // synchronization scope — a render pass WHOLE, a compute dispatch
            // over its FULL bound groups; no visibility filter, no static-use
            // filter — a buffer presents ONE writability. Mixed-writability
            // faces of one buffer never share a layout and are never co-bound
            // in one scope. Witnesses: P-scope render arm + compute arm +
            // the group-local law. Pessimism is the law: no relaxation on a
            // citation — only on a witnessed Dawn behavior test.
            // ──────────────────────────────────────────────────────────────

        } // namespace bind
    } // namespace the_board
} // namespace t7
