#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════════
# THE ONE TABLE'S INSTRUMENT (LOOM_1) — binding_gen.py
#
# tools/binding_schema.py is the single authority for the binding
# surface; this tool is its instrument. Treatments per mirror:
#   EMIT   binding_registry.hpp and binding_surface.gen.inc (--write)
#   PATCH  world.wgsl @group/@binding integers only (--write-wgsl PATH)
#   CHECK  everything, both directions (--check)
#
# AUTHORITY DIRECTION. At U1 the TREE is the authority and the schema is
# corrected to match it (--bootstrap parses the tree and prints a schema
# module to STDOUT ONLY — this tool can never write the authority file
# itself). From U2 onward, per flipped mirror, the SCHEMA is the
# authority: --check must pass at every campaign's recon gate and before
# any commit that touches the surface.
#
# PARSER REUSE. All parsing is imported from binding_ledger.py and
# mirror_census.py — one parse, all instruments. What this file adds is
# capture of the residue LOOM_0 censused (verbatim prose, trailing
# comments, band structure, formatting) and the emitters.
#
# USAGE
#   python3 tools/binding_gen.py --bootstrap        # schema module -> stdout
#   python3 tools/binding_gen.py --check            # tree vs schema, both ways
#   python3 tools/binding_gen.py --write            # emit registry + .gen.inc
#   python3 tools/binding_gen.py --write-wgsl PATH  # renumber decls in PATH
#
# Exit status: --check is 1 on any relation mismatch, emission
# divergence, or witness failure; emit targets that do not exist yet are
# reported as "target not yet generated" and are not failures.
# Every write pins encoding="utf-8", newline="\n" and byte-verifies
# LF-only, no BOM, exactly one trailing newline after writing.
# ═══════════════════════════════════════════════════════════════════════

import argparse
import importlib.util
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))


def _load(name):
    spec = importlib.util.spec_from_file_location(
        name, os.path.join(_HERE, name + ".py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


BL = _load("binding_ledger")
MC = _load("mirror_census")

REPO = BL.REPO
REGISTRY_HPP = BL.REGISTRY_HPP
STATE_HPP = BL.STATE_HPP
WORLD_WGSL = BL.WORLD_WGSL
GEN_INC = os.path.join(BL.REAL, "binding_surface.gen.inc")
SCHEMA_PATH = os.path.join(_HERE, "binding_schema.py")
LEDGER_MD = os.path.join(REPO, "audit", "BINDING_LEDGER.md")

NOTICE = ("GENERATED by tools/binding_gen.py from tools/binding_schema.py "
          "\u2014 do not hand-edit")

VIS_EMIT = {"V": "wgpu::ShaderStage::Vertex",
            "F": "wgpu::ShaderStage::Fragment",
            "C": "wgpu::ShaderStage::Compute"}


def stop(msg):
    sys.stderr.write("STOP \u2014 %s\n" % msg)
    sys.exit(1)


def write_file(path, text):
    """The G2-eol pattern: pinned writer, byte-level read-back."""
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    bx = BL.verify_bytes(path)
    if bx["crlf"] or bx["cr"] or bx["bom"] or not bx["trailing"]:
        stop("encoding read-back failed on %s: %r" % (path, bx))
    return bx


# ═══════════════════════════════════════════════════════════════════════
# CAPTURE — the tree parsed into the schema's shape
# ═══════════════════════════════════════════════════════════════════════

def _dedent_uniform(lines, where):
    """Strip one uniform indentation from a verbatim line group."""
    pad = None
    for ln in lines:
        if not ln.strip():
            continue
        p = len(ln) - len(ln.lstrip(" "))
        pad = p if pad is None else min(pad, p)
    pad = pad or 0
    for ln in lines:
        if ln.strip() and (len(ln) - len(ln.lstrip(" "))) < pad:
            stop("ragged indentation in %s: %r" % (where, ln))
    return [ln[pad:] if ln.strip() else "" for ln in lines]


def segment_registry():
    """binding_registry.hpp -> file banner, namespace/band structure,
    constants with their verbatim lines, the invariants block."""
    raw = BL.read(REGISTRY_HPP)
    lines = raw.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]
    i = 0
    if not lines[i].startswith("#pragma once"):
        stop("registry does not start with #pragma once: %r" % lines[i])
    i += 1
    banner = []
    while lines[i].startswith("//"):
        banner.append(lines[i])
        i += 1
    for want in ("#include <cstdint>", "", "namespace t7 {",
                 "    namespace the_board {", "        namespace bind {"):
        if lines[i] != want:
            stop("registry skeleton: expected %r, found %r" % (want, lines[i]))
        i += 1

    consts = {}
    namespaces = []
    while True:
        # a namespace section: blank, banner block, open, items, close
        if lines[i] != "":
            break
        i += 1
        ns_banner = []
        while lines[i].lstrip().startswith("//"):
            ns_banner.append(lines[i])
            i += 1
        m = re.fullmatch(r"\s*namespace (g\d) \{", lines[i])
        if not m:
            stop("registry skeleton: expected namespace open, found %r" % lines[i])
        name = m.group(1)
        i += 1
        bands = []
        cur = None
        gap = 0
        while not re.fullmatch(r"\s*\} // namespace %s" % name, lines[i]):
            ln = lines[i]
            if ln.strip() == "":
                gap += 1
                i += 1
                continue
            if ln.lstrip().startswith("//"):
                blk = []
                while lines[i].lstrip().startswith("//"):
                    blk.append(lines[i])
                    i += 1
                cur = {"gap_before": gap,
                       "banner": _dedent_uniform(blk, "band banner in " + name),
                       "constants": []}
                bands.append(cur)
                gap = 0
                continue
            cm = re.fullmatch(
                r"\s*inline constexpr uint32_t (\w+)\s+= (\d+);(?:\s*// ?(.*))?",
                ln)
            if not cm:
                stop("registry: unparseable line in %s: %r" % (name, ln))
            if gap:
                stop("registry: blank line inside a constant run before %r "
                     "\u2014 the band model cannot carry it" % ln)
            if cur is None:
                cur = {"gap_before": 0, "banner": None, "constants": []}
                bands.append(cur)
            cur["constants"].append(cm.group(1))
            consts[cm.group(1)] = {
                "namespace": name,
                "binding": int(cm.group(2)),
                "trailing_comment": cm.group(3) if cm.group(3) is not None else None,
                "text": ln.strip(),
            }
            i += 1
        i += 1
        namespaces.append({"name": name,
                           "banner": _dedent_uniform(ns_banner,
                                                     "banner of " + name),
                           "bands": bands})
        if not (lines[i] == "" and lines[i + 1].lstrip().startswith("//")
                and "namespace g" not in lines[i + 1]):
            # not another namespace section: fall through to invariants
            if not re.fullmatch(r"\s*namespace g\d \{", lines[i + 1].strip() + " {") :
                pass
        # peek: another namespace?
        j = i
        if lines[j] == "":
            k = j + 1
            while k < len(lines) and lines[k].lstrip().startswith("//"):
                k += 1
            if k < len(lines) and re.fullmatch(r"\s*namespace g\d \{", lines[k]):
                continue
        break

    if lines[i] != "":
        stop("registry skeleton: expected blank before invariants, found %r"
             % lines[i])
    i += 1
    inv = []
    while lines[i].strip() != "":
        inv.append(lines[i])
        i += 1
    i += 1
    for want in ("        } // namespace bind", "    } // namespace the_board",
                 "} // namespace t7"):
        if lines[i] != want:
            stop("registry skeleton: expected %r, found %r" % (want, lines[i]))
        i += 1
    if i != len(lines):
        stop("registry skeleton: %d trailing line(s) after the closes"
             % (len(lines) - i))
    return {"file_banner": banner, "namespaces": namespaces,
            "constants": consts,
            "invariants": _dedent_uniform(inv, "invariants block")}


def _prose_above(lines, idx):
    """Comment runs (with internal blanks) directly above lines[idx],
    walking up until code. Returns verbatim lines, blank-trimmed."""
    out = []
    j = idx - 1
    while j >= 0:
        s = lines[j].strip()
        if s == "" or s.startswith("//"):
            out.append(lines[j])
            j -= 1
        else:
            break
    out.reverse()
    while out and out[0].strip() == "":
        out.pop(0)
    while out and out[-1].strip() == "":
        out.pop()
    if not any(x.strip() for x in out):
        return None
    return _dedent_uniform(out, "prose above line %d" % (idx + 1))


class BlockCapture:
    """Prose and trailing comments for one state.hpp creation block."""
    __slots__ = ("exterior", "seat_prose", "trailing", "min_binding",
                 "local_constants", "start_line", "brace_line")


def capture_state_blocks(kind_re, create_token):
    """For each block (file order): exterior prose above the opening
    brace, per-seat leading prose, per-statement trailing comments,
    minBindingSize expressions, in-block constants. All verbatim."""
    raw = BL.read(STATE_HPP)
    src = BL.strip_cpp_comments(raw)
    rawlines = raw.split("\n")
    out = []
    for m in re.finditer(
            r"std::array<\s*wgpu::" + kind_re + r"\s*,\s*(\d+)\s*>\s*(\w+)\s*\{\s*\}\s*;",
            src):
        tail = src.find(create_token, m.end())
        end = src.find(";", tail) + 1
        cap = BlockCapture()
        cap.start_line = BL.line_of(src, m.start())
        # the opening brace of the block's scope, walking up raw lines
        bi = cap.start_line - 2
        while bi >= 0 and rawlines[bi].strip() in ("", "{"):
            if rawlines[bi].strip() == "{":
                break
            bi -= 1
        if bi < 0 or rawlines[bi].strip() != "{":
            # the builder block opens with the lambda header, not a bare {
            hm = re.search(r"->\s*wgpu::BindGroup\s*\{\s*$", rawlines[cap.start_line - 2])
            if hm:
                bi = cap.start_line - 2
                while bi >= 0 and "auto build_render_entity_group" not in rawlines[bi]:
                    bi -= 1
            else:
                stop("state.hpp block at line %d has no enclosing '{' line"
                     % cap.start_line)
        cap.brace_line = bi + 1
        cap.exterior = _prose_above(rawlines, bi)
        cap.seat_prose = {}
        cap.trailing = {}
        cap.min_binding = {}
        cap.local_constants = []
        block_src = src[m.start():end]
        for e in re.finditer(r"entries\[(\d+)\]\.([\w.]+)\s*=", block_src):
            idx = int(e.group(1))
            field = e.group(2)
            ln = BL.line_of(src, m.start() + e.start())
            if field == "binding":
                p = _prose_above(rawlines, ln - 1)
                if p:
                    cap.seat_prose[idx] = p
            tm = re.match(r".*;\s+(// .*)$", rawlines[ln - 1])
            if tm:
                cap.trailing[(idx, field)] = tm.group(1)
            if field == "buffer.minBindingSize":
                vm = re.search(r"=\s*([^;]+);", rawlines[ln - 1])
                cap.min_binding[idx] = vm.group(1).strip()
        for cm_ in re.finditer(r"static constexpr uint32_t[^;]+;", block_src):
            a, b_ = MC.tight_span(block_src, cm_.start(), cm_.end())
            cap.local_constants.append(MC.norm(raw[m.start() + a:m.start() + b_]))
        out.append(cap)
    return out


def resolve_seat_decl(entry, slots):
    """Seat -> DECL symbol, by access compatibility; this is what makes
    the vp_data/fc_vp aliased slot representable. Primary wins ties."""
    grp = int(entry.registry_ns[1])
    cands = slots.get((grp, entry.binding_number), [])

    def compat(d):
        if entry.kind == "buffer":
            if d.address_space == "uniform":
                return entry.access == "Uniform"
            if d.address_space == "storage":
                return ((entry.access == "Storage" and d.wgsl_access == "read_write")
                        or (entry.access == "ReadOnlyStorage" and d.wgsl_access == "read"))
            return False
        return d.address_space == "handle"

    ok = [d for d in cands if compat(d)]
    if not ok:
        stop("no access-compatible declaration for seat %s entries[%d] (%s %s)"
             % (entry.layout_label, entry.entry_index, entry.kind, entry.access))
    ok.sort(key=lambda d: d.line)
    return ok[0].symbol


def capture_tree():
    """The whole tree, parsed into the schema module's exact shape."""
    w = BL.Witnesses()
    registry_consts = BL.parse_registry(w)
    layouts = BL.parse_layouts(w, registry_consts)
    b = BL.phase_0b(w)
    c = BL.phase_0c(w, layouts, b)
    groups, invokes = MC.parse_groups(w)
    bad = w.failures()
    if bad:
        stop("imported parsers report failures: %s"
             % "; ".join(t for t, _, _ in bad))

    # ─── DECLS ────────────────────────────────────────────────────────
    decls = {}
    primary = {}
    for d in sorted(b["decls"], key=lambda d: d.line):
        slot = (d.group, d.binding)
        decls[d.symbol] = {
            "group": d.group,
            "binding": d.binding,
            "address_space": d.address_space,
            "access": d.wgsl_access if d.address_space == "storage" else None,
            "store_type": d.wgsl_type,
            "alias_of": primary.get(slot),
        }
        primary.setdefault(slot, d.symbol)

    # Per-decl C++ seat-type facts. Filtering vs NonFiltering and Float
    # vs UnfilterableFloat are C++-side choices no WGSL spelling caries,
    # so they are schema columns; one value per DECL, asserted here.
    cpp = {}
    for L in layouts:
        for e in L["entries"]:
            sym = resolve_seat_decl(e, b["slots"])
            if e.kind == "buffer":
                fact = ("buffer", e.access)
            elif e.kind == "sampler":
                fact = ("sampler", e.access)
            elif e.kind == "texture":
                s_, dim = e.access.split("/")
                fact = ("texture", s_, dim)
            else:
                a_, f_, dim = e.access.split("/")
                fact = ("storageTexture", a_, f_, dim)
            if sym in cpp and cpp[sym] != fact:
                stop("decl %s carries two seat-type facts: %r vs %r"
                     % (sym, cpp[sym], fact))
            cpp[sym] = fact
    for sym, fact in cpp.items():
        decls[sym]["cpp"] = fact
    for sym in decls:
        decls[sym].setdefault("cpp", None)   # never bound by any layout

    # ─── REGISTRY ─────────────────────────────────────────────────────
    seg = segment_registry()
    for name, row in seg["constants"].items():
        if registry_consts.get((row["namespace"], name)) != row["binding"]:
            stop("registry segmentation disagrees with parse_registry at %s" % name)

    # ─── SEATS ────────────────────────────────────────────────────────
    layout_caps = capture_state_blocks(r"BindGroupLayoutEntry",
                                       "CreateBindGroupLayout")
    if len(layout_caps) != len(layouts):
        stop("layout capture count %d != parsed layouts %d"
             % (len(layout_caps), len(layouts)))
    seats = {}
    for L, cap in zip(layouts, layout_caps):
        for e in L["entries"]:
            tr = {f: t for (i, f), t in cap.trailing.items() if i == e.entry_index}
            seats[(L["member"], e.entry_index)] = {
                "decl": resolve_seat_decl(e, b["slots"]),
                "visibility": "|".join(e.vis_declared),
                "has_dynamic_offset": e.has_dynamic_offset,
                "min_binding_size": cap.min_binding.get(e.entry_index),
                "prose": cap.seat_prose.get(e.entry_index),
                "trailing": tr,
            }

    # ─── LAYOUTS ──────────────────────────────────────────────────────
    acc = MC.accessor_map()
    layouts_rel = {}
    for L, cap in zip(layouts, layout_caps):
        a_ = acc.get(L["member"], [])
        if len(a_) != 1:
            stop("layout %s resolves to %d accessors" % (L["member"], len(a_)))
        layouts_rel[L["member"]] = {"label": L["label"], "accessor": a_[0],
                                    "prose": cap.exterior}

    # ─── GROUPS ───────────────────────────────────────────────────────
    group_caps = capture_state_blocks(r"BindGroupEntry", "CreateBindGroup(")
    if len(group_caps) != len(groups):
        stop("group capture count %d != parsed groups %d"
             % (len(group_caps), len(groups)))
    by_member = {L["member"]: L for L in layouts}
    groups_rel = {}
    for g, cap in zip(groups, group_caps):
        lay = by_member.get(g["layout_member"])
        if lay is None:
            stop("group %r: layout %r not parsed" % (g["label"], g["layout_member"]))
        seat_by_const = {e.binding_const: e for e in lay["entries"]}
        entries = {}
        for e in g["entries"]:
            le = seat_by_const.get(e["binding"])
            if le is None or le.entry_index != e["index"]:
                stop("group %r entries[%d] (%s) does not align with layout %s"
                     % (g["label"], e["index"], e["binding"], lay["label"]))
            tr = {f: t for (i, f), t in cap.trailing.items() if i == e["index"]}
            entries[e["index"]] = {
                "decl": resolve_seat_decl(le, b["slots"]),
                "backing": e["backing"],
                "size_expr": e.get("size"),
                "offset_expr": e.get("offset"),
                "prose": cap.seat_prose.get(e["index"]),
                "trailing": tr,
            }
        if g["member"] is None:
            key = "build_render_entity_group"
            cadence = "builder"
        elif g["desc_var"] != "desc":
            key = g["member"]
            cadence = "rebuild"
        else:
            key = g["member"]
            cadence = "boot"
        groups_rel[key] = {
            "label": None if g["param_label"] else g["label"],
            "label_param": g["param_label"],
            "layout": g["layout_member"],
            "cadence": cadence,
            "local_constants": cap.local_constants,
            "prose": cap.exterior,
            "entries": entries,
        }
    if "build_render_entity_group" in groups_rel:
        groups_rel["build_render_entity_group"]["invocations"] = [
            {"member": iv["member"], "label": iv["label"],
             "offset_arg": iv["offset_arg"], "size_arg": iv["size_arg"]}
            for iv in invokes]

    # ─── PIPELINES ────────────────────────────────────────────────────
    ec = c["entry_const"]
    pipelines_rel = {}
    for p in c["pipelines"]:
        pipelines_rel[p.member] = {
            "label": p.label,
            "kind": p.kind,
            "layouts": list(p.group_layouts),
            "vs": ec.get(p.vs_entry) if p.vs_entry else None,
            "fs": ec.get(p.fs_entry) if p.fs_entry else None,
            "cs": ec.get(p.cs_entry) if p.cs_entry else None,
            "vertex_buffers": p.vertex_buffer_count,
            "vertex_attributes": p.vertex_attribute_count,
            "color_targets": p.color_target_count,
            "roster_gate": p.roster_gate,
        }

    return {
        "DECLS": decls,
        "REGISTRY": seg["constants"],
        "REGISTRY_FILE_BANNER": seg["file_banner"],
        "REGISTRY_NAMESPACES": seg["namespaces"],
        "REGISTRY_INVARIANTS": seg["invariants"],
        "SEATS": seats,
        "LAYOUTS": layouts_rel,
        "GROUPS": groups_rel,
        "PIPELINES": pipelines_rel,
    }


# ═══════════════════════════════════════════════════════════════════════
# THE SCHEMA PRINTER (--bootstrap; stdout only, never the file)
# ═══════════════════════════════════════════════════════════════════════

def _fmt(v):
    if isinstance(v, dict):
        return "{" + ", ".join("%s: %s" % (_fmt(k), _fmt(x))
                               for k, x in v.items()) + "}"
    if isinstance(v, (list, tuple)):
        inner = ", ".join(_fmt(x) for x in v)
        return ("(" + inner + ("," if len(v) == 1 else "") + ")"
                if isinstance(v, tuple) else "[" + inner + "]")
    return repr(v)


def print_schema(tree, out=sys.stdout):
    W = out.write
    W('# \u2550\u2550\u2550 THE ONE TABLE (LOOM_1) '
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\n')
    W("# tools/binding_schema.py \u2014 the single authority for the binding\n")
    W("# surface. DATA ONLY, no logic. Edit this file, then run\n")
    W("# tools/binding_gen.py --write; never hand-edit the generated\n")
    W("# mirrors. binding_gen.py --check verifies tree and schema agree\n")
    W("# across all six relations, both directions.\n")
    W("#\n")
    W("# Bootstrapped from the tree by binding_gen.py --bootstrap; prose\n")
    W("# fields carry source text verbatim (dedented; emission re-indents).\n")
    W('# \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
      '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\n')
    for name in ("DECLS", "REGISTRY", "SEATS", "LAYOUTS", "GROUPS",
                 "PIPELINES"):
        rel = tree[name]
        W("\n%s = {\n" % name)
        for k, row in rel.items():
            W("    %s: %s,\n" % (_fmt(k), _fmt(row)))
        W("}\n")
    for name in ("REGISTRY_FILE_BANNER", "REGISTRY_NAMESPACES",
                 "REGISTRY_INVARIANTS"):
        val = tree[name]
        W("\n%s = [\n" % name)
        for item in val:
            W("    %s,\n" % _fmt(item))
        W("]\n")


# ═══════════════════════════════════════════════════════════════════════
# EMISSION
# ═══════════════════════════════════════════════════════════════════════

def emit_registry(schema, with_notice=True):
    L = []
    L.append("#pragma once" + ("  // " + NOTICE if with_notice else ""))
    L.extend(schema.REGISTRY_FILE_BANNER)
    L.append("#include <cstdint>")
    L.append("")
    L.append("namespace t7 {")
    L.append("    namespace the_board {")
    L.append("        namespace bind {")
    for ns in schema.REGISTRY_NAMESPACES:
        L.append("")
        for ln in ns["banner"]:
            L.append(("            " + ln) if ln else "")
        L.append("            namespace %s {" % ns["name"])
        for band in ns["bands"]:
            L.extend([""] * band["gap_before"])
            if band["banner"]:
                for ln in band["banner"]:
                    L.append(("                " + ln) if ln else "")
            for cname in band["constants"]:
                L.append("                " + schema.REGISTRY[cname]["text"])
        L.append("            } // namespace %s" % ns["name"])
    L.append("")
    for ln in schema.REGISTRY_INVARIANTS:
        L.append(("            " + ln) if ln else "")
    L.append("")
    L.append("        } // namespace bind")
    L.append("    } // namespace the_board")
    L.append("} // namespace t7")
    return "\n".join(L) + "\n"


def _slot_const(schema, decl_sym):
    """DECL symbol -> the registry constant naming its slot."""
    d = schema.DECLS[decl_sym]
    prim = d["alias_of"] or decl_sym
    ns = "g%d" % d["group"]
    row = schema.REGISTRY.get(prim)
    if row is None or row["namespace"] != ns or row["binding"] != d["binding"]:
        stop("no registry constant for decl %s at (%d, %d)"
             % (decl_sym, d["group"], d["binding"]))
    return "bind::%s::%s" % (ns, prim)


def _seat_type_lines(schema, seat, ind):
    """The type-specific statements of one layout seat."""
    d = schema.DECLS[seat["decl"]]
    fact = d["cpp"]
    i = seat_index = seat["_index"]
    t = seat.get("trailing", {})

    def line(field, value):
        c = t.get(field)
        return "%sentries[%d].%s = %s;%s" % (ind, i, field, value,
                                             ("  " + c) if c else "")
    out = []
    if fact[0] == "buffer":
        out.append(line("buffer.type", "wgpu::BufferBindingType::" + fact[1]))
        if seat["has_dynamic_offset"]:
            out.append(line("buffer.hasDynamicOffset", "true"))
        if seat["min_binding_size"]:
            out.append(line("buffer.minBindingSize", seat["min_binding_size"]))
    elif fact[0] == "sampler":
        out.append(line("sampler.type", "wgpu::SamplerBindingType::" + fact[1]))
    elif fact[0] == "texture":
        out.append(line("texture.sampleType", "wgpu::TextureSampleType::" + fact[1]))
        out.append(line("texture.viewDimension",
                        "wgpu::TextureViewDimension::" + fact[2]))
    else:
        out.append(line("storageTexture.access",
                        "wgpu::StorageTextureAccess::" + fact[1]))
        out.append(line("storageTexture.format", "wgpu::TextureFormat::" + fact[2]))
        out.append(line("storageTexture.viewDimension",
                        "wgpu::TextureViewDimension::" + fact[3]))
    return out


def emit_gen_inc(schema, class_indent="            "):
    """binding_surface.gen.inc \u2014 three GPUState member functions.
    Canonical statement order: seats index-ascending, fields binding /
    visibility / type facts; visibility operands in V|F|C order."""
    ind0 = class_indent                  # member-function signature
    ind1 = ind0 + "    "                 # function body / block braces
    ind2 = ind1 + "    "                 # statements inside a block
    L = []
    bar = "// " + "\u2500" * 68
    L.append(ind0 + bar)
    L.append(ind0 + "// " + NOTICE)
    L.append(ind0 + "// The binding-surface creation blocks, emitted from the schema's")
    L.append(ind0 + "// SEATS / LAYOUTS / GROUPS relations. Seat prose travels from the")
    L.append(ind0 + "// schema verbatim. Statement order is canonical: seats ascend by")
    L.append(ind0 + "// entry index; visibility operands are in Vertex/Fragment/Compute")
    L.append(ind0 + "// order.")
    L.append(ind0 + bar)

    def prose(lines_, ind):
        return [(ind + ln) if ln else "" for ln in (lines_ or [])]

    # ─── the 25 layouts ───────────────────────────────────────────────
    L.append("")
    L.append(ind0 + "bool create_binding_layouts() {")
    seats_by_layout = {}
    for (member, idx), s in schema.SEATS.items():
        seats_by_layout.setdefault(member, {})[idx] = dict(s, _index=idx)
    for member, row in schema.LAYOUTS.items():
        seats = seats_by_layout.get(member, {})
        L.extend(prose(row.get("prose"), ind1))
        L.append(ind1 + "{")
        L.append(ind2 + "std::array<wgpu::BindGroupLayoutEntry, %d> entries{};"
                 % len(seats))
        for idx in sorted(seats):
            s = seats[idx]
            L.append("")
            L.extend(prose(s.get("prose"), ind2))
            t = s.get("trailing", {})
            c = t.get("binding")
            L.append("%sentries[%d].binding = %s;%s"
                     % (ind2, idx, _slot_const(schema, s["decl"]),
                        ("  " + c) if c else ""))
            vis = " | ".join(VIS_EMIT[v] for v in s["visibility"].split("|"))
            c = t.get("visibility")
            L.append("%sentries[%d].visibility = %s;%s"
                     % (ind2, idx, vis, ("  " + c) if c else ""))
            L.extend(_seat_type_lines(schema, s, ind2))
        L.append("")
        L.append(ind2 + "wgpu::BindGroupLayoutDescriptor desc{};")
        L.append(ind2 + 'desc.label = "%s";' % row["label"])
        L.append(ind2 + "desc.entryCount = entries.size();")
        L.append(ind2 + "desc.entries = entries.data();")
        L.append(ind2 + "%s = device_.CreateBindGroupLayout(&desc);" % member)
        L.append(ind2 + "if (!%s) return false;" % member)
        L.append(ind1 + "}")
    L.append(ind1 + "return true;")
    L.append(ind0 + "}")

    # ─── the bind groups ──────────────────────────────────────────────
    def group_block(key, row, ind_a, ind_b, tail):
        out = []
        out.extend(prose(row.get("prose"), ind_a))
        opener = (ind_a + "{") if key != "build_render_entity_group" else (
            ind_a + "auto build_render_entity_group = [&](const char* label, "
                    "uint32_t listOff, uint32_t listBytes) -> wgpu::BindGroup {")
        out.append(opener)
        entries = row["entries"]
        out.append(ind_b + "std::array<wgpu::BindGroupEntry, %d> entries{};"
                   % len(entries))
        for lc in row.get("local_constants", []):
            out.append(ind_b + lc)
        for idx in sorted(entries):
            e = entries[idx]
            out.append("")
            out.extend(prose(e.get("prose"), ind_b))
            t = e.get("trailing", {})
            c = t.get("binding")
            out.append("%sentries[%d].binding = %s;%s"
                       % (ind_b, idx, _slot_const(schema, e["decl"]),
                          ("  " + c) if c else ""))
            d = schema.DECLS[e["decl"]]
            field = {"buffer": "buffer", "sampler": "sampler",
                     "texture": "textureView",
                     "storageTexture": "textureView"}[d["cpp"][0]]
            c = t.get(field)
            out.append("%sentries[%d].%s = %s;%s"
                       % (ind_b, idx, field, e["backing"],
                          ("  " + c) if c else ""))
            if e.get("offset_expr") is not None:
                c = t.get("offset")
                out.append("%sentries[%d].offset = %s;%s"
                           % (ind_b, idx, e["offset_expr"],
                              ("  " + c) if c else ""))
            if e.get("size_expr") is not None:
                c = t.get("size")
                out.append("%sentries[%d].size = %s;%s"
                           % (ind_b, idx, e["size_expr"],
                              ("  " + c) if c else ""))
        out.append("")
        out.append(ind_b + "wgpu::BindGroupDescriptor desc{};")
        if row["label_param"]:
            out.append(ind_b + "desc.label = label;")
        else:
            out.append(ind_b + 'desc.label = "%s";' % row["label"])
        out.append(ind_b + "desc.layout = %s;" % row["layout"])
        out.append(ind_b + "desc.entryCount = entries.size();")
        out.append(ind_b + "desc.entries = entries.data();")
        out.extend(tail)
        return out

    L.append("")
    L.append(ind0 + "bool create_binding_groups_boot() {")
    for key, row in schema.GROUPS.items():
        if row["cadence"] == "rebuild":
            continue
        if row["cadence"] == "builder":
            L.extend(group_block(key, row, ind1, ind2, [
                ind2 + "return device_.CreateBindGroup(&desc);",
                ind1 + "};"]))
            for iv in row["invocations"]:
                L.append(ind1 + '%s = build_render_entity_group("%s", %s, %s);'
                         % (iv["member"], iv["label"], iv["offset_arg"],
                            iv["size_arg"]))
            L.append(ind1 + "if (%s) return false;"
                     % " || ".join("!" + iv["member"] for iv in row["invocations"]))
        else:
            L.extend(group_block(key, row, ind1, ind2, [
                ind2 + "%s = device_.CreateBindGroup(&desc);" % key,
                ind2 + "if (!%s) return false;" % key,
                ind1 + "}"]))
    L.append(ind1 + "return true;")
    L.append(ind0 + "}")

    L.append("")
    L.append(ind0 + "// Callable at boot and at the exhibition rebuild \u2014 the one bind")
    L.append(ind0 + "// group re-made after boot, against the exhibition read view.")
    L.append(ind0 + "bool create_gallery_texture_group() {")
    for key, row in schema.GROUPS.items():
        if row["cadence"] != "rebuild":
            continue
        L.extend(group_block(key, row, ind1, ind2, [
            ind2 + "%s = device_.CreateBindGroup(&desc);" % key,
            ind2 + "if (!%s) return false;" % key,
            ind1 + "}"]))
    L.append(ind1 + "return true;")
    L.append(ind0 + "}")
    return "\n".join(L) + "\n"


def rewrite_wgsl(schema, raw):
    """Symbol-anchored renumber of the 98 declaration sites: only the
    @group / @binding integers change; prose, scatter, spacing stay."""
    out = raw
    for sym, row in schema.DECLS.items():
        pat = re.compile(
            r"(@group\()(\d+)(\)\s*@binding\()(\d+)(\)\s*var(?:<[^>]*>)?\s+%s\s*:)"
            % re.escape(sym))
        ms = list(pat.finditer(out))
        if len(ms) != 1:
            stop("write-wgsl anchor for %r matches %d times; site(s): %s"
                 % (sym, len(ms),
                    "; ".join(MC.norm(m.group(0)) for m in ms) or "none"))
        out = pat.sub(lambda m: "%s%d%s%d%s" % (m.group(1), row["group"],
                                                m.group(3), row["binding"],
                                                m.group(5)), out, count=1)
    return out


# ═══════════════════════════════════════════════════════════════════════
# CHECK
# ═══════════════════════════════════════════════════════════════════════

def load_schema():
    if not os.path.exists(SCHEMA_PATH):
        stop("tools/binding_schema.py does not exist \u2014 run --bootstrap "
             "and review its output into place")
    return _load("binding_schema")


def diff_relation(name, tree_rel, schema_rel, out):
    """Symbol-keyed, both directions."""
    bad = 0
    tk, sk = set(tree_rel), set(schema_rel)
    for k in sorted(tk - sk, key=repr):
        out.append("  %s: %r in tree, absent from schema" % (name, k))
        bad += 1
    for k in sorted(sk - tk, key=repr):
        out.append("  %s: %r in schema, absent from tree" % (name, k))
        bad += 1
    for k in sorted(tk & sk, key=repr):
        t, s = tree_rel[k], schema_rel[k]
        if isinstance(t, dict) and isinstance(s, dict):
            for col in sorted(set(t) | set(s)):
                if t.get(col) != s.get(col):
                    out.append("  %s[%r].%s: tree %r, schema %r"
                               % (name, k, col, t.get(col), s.get(col)))
                    bad += 1
        elif t != s:
            out.append("  %s[%r]: tree %r, schema %r" % (name, k, t, s))
            bad += 1
    return bad


def ledger_cardinalities():
    led = BL.read(LEDGER_MD)
    m1 = re.search(r"(\d+) module-scope declarations over (\d+) `\(group, binding\)` slots", led)
    m2 = re.search(r"One row per `\(bind group layout, entry index\)`, (\d+) rows over (\d+) layouts", led)
    m3 = re.search(r"(\d+) bind groups over (\d+) layouts, every one a bijection", led)
    m4 = re.search(r"(\d+) pipelines: \d+ with exactly one call shape", led)
    if not (m1 and m2 and m3 and m4):
        stop("the ledger does not state its counts \u2014 S-1 cannot read its authority")
    return {"decls": int(m1.group(1)), "slots": int(m1.group(2)),
            "seats": int(m2.group(1)), "layouts": int(m2.group(2)),
            "groups": int(m3.group(1)), "pipelines": int(m4.group(1))}


def table_h_sites():
    led = BL.read(LEDGER_MD)
    rows = []
    for m in re.finditer(r"^\| `([^`]+)` \| ([\w ]+) \| `([^`]+)` \| \d+ \| ([^|]+) \|",
                        led, re.M):
        trig = [t.strip().strip("`") for t in m.group(4).split(",")]
        rows.append({"symbol": m.group(1), "kind": m.group(2).strip(),
                     "file": m.group(3), "triggers": trig})
    return rows


def check(args):
    tree = capture_tree()
    schema = load_schema()
    problems = []
    print("binding_gen --check")
    print("")
    print("RELATIONS (tree vs schema, both directions)")
    n = 0
    for name in ("DECLS", "REGISTRY", "SEATS", "LAYOUTS", "GROUPS",
                 "PIPELINES"):
        lines = []
        n += diff_relation(name, tree[name], getattr(schema, name), lines)
        print("  %-9s %4d rows  %s"
              % (name, len(tree[name]), "agree" if not lines else "MISMATCH"))
        for ln in lines[:40]:
            print("  " + ln)
        problems.extend(lines)
    for name in ("REGISTRY_FILE_BANNER", "REGISTRY_NAMESPACES",
                 "REGISTRY_INVARIANTS"):
        same = tree[name] == getattr(schema, name)
        print("  %-22s %s" % (name, "agree" if same else "MISMATCH"))
        if not same:
            problems.append("%s differs" % name)

    print("")
    print("EMIT TARGETS (schema -> bytes vs disk)")
    disk = BL.read(REGISTRY_HPP)
    flipped = NOTICE in disk.split("\n", 1)[0]
    want = emit_registry(schema, with_notice=flipped)
    tag = "generated" if flipped else "target not yet generated; pre-flip equivalence"
    same = want == disk
    print("  binding_registry.hpp: %s \u2014 %s" % (tag, "OK" if same else "DIVERGES"))
    if not same:
        for i, (a, b_) in enumerate(zip(disk.split("\n"), want.split("\n")), 1):
            if a != b_:
                print("    first divergence at line %d:\n      disk: %r\n      emit: %r"
                      % (i, a, b_))
                break
        problems.append("registry emission diverges from disk")
    if os.path.exists(GEN_INC):
        same = emit_gen_inc(schema) == BL.read(GEN_INC)
        print("  binding_surface.gen.inc: generated \u2014 %s"
              % ("OK" if same else "DIVERGES"))
        if not same:
            problems.append("gen.inc emission diverges from disk")
    else:
        print("  binding_surface.gen.inc: target not yet generated")

    print("")
    print("WITNESSES")
    card = ledger_cardinalities()
    slots = len({(d["group"], d["binding"]) for d in schema.DECLS.values()})
    got = (len(schema.DECLS), slots, len(schema.SEATS), len(schema.LAYOUTS),
           len(schema.GROUPS), len(schema.PIPELINES))
    wantc = (card["decls"], card["slots"], card["seats"], card["layouts"],
             card["groups"], card["pipelines"])
    ok = got == wantc
    print("  [%s] S-1  schema cardinalities equal the ledger's: %s vs %s"
          % ("PASS" if ok else "FAIL",
             "/".join(str(x) for x in got), "/".join(str(x) for x in wantc)))
    if not ok:
        problems.append("S-1 cardinality mismatch")

    # S-2: the defended text survived transcription. For every Table H
    # site in the registry or the layout blocks, each of its triggers
    # must match the schema's concatenated prose for that relation.
    prose_reg = "\n".join(
        ["\n".join(schema.REGISTRY_FILE_BANNER)] +
        ["\n".join(b["banner"]) for ns in schema.REGISTRY_NAMESPACES
         for b in ns["bands"] if b["banner"]] +
        ["\n".join(ns["banner"]) for ns in schema.REGISTRY_NAMESPACES] +
        [r["text"] for r in schema.REGISTRY.values()] +
        ["\n".join(schema.REGISTRY_INVARIANTS)])
    prose_seats = "\n".join(
        ["\n".join(s["prose"]) for s in schema.SEATS.values() if s["prose"]] +
        [t for s in schema.SEATS.values() for t in s["trailing"].values()] +
        ["\n".join(r["prose"]) for r in schema.LAYOUTS.values() if r["prose"]])
    trig_pat = dict(BL.TRIGGERS)
    missing = []
    checked = 0
    for site in table_h_sites():
        if "binding_registry.hpp" in site["file"] and site["kind"] in (
                "file", "registry constant"):
            hay = prose_reg
        elif "state.hpp" in site["file"] and site["kind"] in (
                "layout", "layout entry"):
            hay = prose_seats
        else:
            continue
        checked += 1
        for t in site["triggers"]:
            pat = trig_pat.get(t)
            if pat is None or not re.search(
                    pat, hay, re.I if t != "law-ref" else 0):
                missing.append("%s (%s): trigger %s not found"
                               % (site["symbol"], site["kind"], t))
    ok = not missing
    print("  [%s] S-2  %d Table H sites in the transcribed mirrors; every "
          "trigger matches the schema's prose%s"
          % ("PASS" if ok else "FAIL", checked,
             "" if ok else " \u2014 MISSING: " + "; ".join(missing)))
    if not ok:
        problems.append("S-2 trigger loss")

    # S-3 (in memory): renumber with unchanged numbers is the identity.
    raw = BL.read(WORLD_WGSL)
    ok = rewrite_wgsl(schema, raw) == raw
    print("  [%s] S-3  --write-wgsl round-trip with unchanged numbers is "
          "the identity on world.wgsl" % ("PASS" if ok else "FAIL"))
    if not ok:
        problems.append("S-3 wgsl round-trip diverges")

    print("")
    if problems:
        print("STOP \u2014 %d problem(s); the schema and the tree disagree, or "
              "an emitter diverges." % len(problems))
        return 1
    print("--check: all relations agree, all witnesses pass.")
    return 0


# ═══════════════════════════════════════════════════════════════════════

def main():
    ap = argparse.ArgumentParser(description="LOOM_1 \u2014 the one table's instrument.")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--bootstrap", action="store_true",
                   help="parse the tree, print a schema module to stdout")
    g.add_argument("--check", action="store_true",
                   help="diff tree against schema, verify emitters and witnesses")
    g.add_argument("--write", action="store_true",
                   help="emit binding_registry.hpp and binding_surface.gen.inc")
    g.add_argument("--write-wgsl", metavar="PATH",
                   help="renumber the declaration sites of the file at PATH")
    args = ap.parse_args()

    if args.bootstrap:
        print_schema(capture_tree())
        return 0
    if args.check:
        return check(args)
    if args.write:
        schema = load_schema()
        write_file(REGISTRY_HPP, emit_registry(schema, with_notice=True))
        print("wrote %s" % os.path.relpath(REGISTRY_HPP, REPO))
        write_file(GEN_INC, emit_gen_inc(schema))
        print("wrote %s" % os.path.relpath(GEN_INC, REPO))
        return 0
    if args.write_wgsl:
        schema = load_schema()
        raw = BL.read(args.write_wgsl)
        write_file(args.write_wgsl, rewrite_wgsl(schema, raw))
        print("wrote %s" % args.write_wgsl)
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
