#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════════
# PURSE_0 R2 — THE BUILD STAMP
#
# The program states its own provenance at boot. Two shas end the
# which-program-am-I-looking-at class of question permanently, and they
# answer different halves of it:
#
#   the wasm sha (web_dist.py's __BUILD_ID__)  names the ARTIFACT
#   the git sha  (this file's BUILD_STAMP)      names the TREE
#
# One without the other leaves a gap. A matching artifact digest says the
# browser got the bytes the build produced; it says nothing about WHICH
# tree produced them. A git sha alone says nothing about whether the
# browser is running a cached predecessor.
#
# ── WHY THIS WRITES TO THE BUILD DIRECTORY, NOT THE SOURCE TREE ────────
#
# Every other generated file in this tree (binding_surface.gen.inc,
# limits_floor.gen.inc, features_wallet.gen.inc, the five in audit/) is
# TRACKED, written by a named tool run BY HAND, and asserted byte-identical
# by a gate. That model cannot hold a build stamp, and the reason is not
# taste:
#
#   1. The stamp carries a UTC instant, so a build rewrites it. A tracked
#      file rewritten by every build makes the working tree dirty after
#      every build, and the binding gate's S-6 witness — "porcelain clean;
#      HEAD == pushed tip" — would then be RED for the life of the tree.
#   2. `git describe --dirty` would report `-dirty` because of its OWN
#      output. Self-referential dirt, and it would never clear.
#   3. Committing the stamp changes the commit the stamp names. The chase
#      does not converge (the ledgers' provenance chase does, because a
#      ledger names the commit BEFORE it; a stamp names the commit it is
#      part of).
#
# So the stamp lands in ${CMAKE_CURRENT_BINARY_DIR}, untracked, on the
# include path. The source tree stays clean, S-6 stays green, and
# `--dirty` reports the tree honestly because the stamp is not in it.
#
# ── WRITE-ON-CHANGE ────────────────────────────────────────────────────
#
# The step is ALWAYS OUT OF DATE by construction (that is the only way to
# observe HEAD moving without a reconfigure), so it runs on every build.
# It rewrites the file only when the STRING differs, which is what keeps
# an always-run step from relinking a binary that has not changed. Two
# builds a minute apart with no commit between them touch nothing.
#
# Usage:  python3 tools/build_stamp.py <output-path>
# ═══════════════════════════════════════════════════════════════════════

import datetime
import os
import subprocess
import sys

# realpath, not abspath: a symlinked checkout (or a tools/ symlinked into a
# scratch build) would otherwise resolve REPO to a directory with no .git
# and stamp `unknown` from a tree that has a perfectly good sha.
REPO = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

# THE UNKNOWN IS A VALUE, NOT AN ERROR. A tarball with no .git is a legal
# way to build this program, and a stamp that says "unknown" is honest
# where a stamp that fails the build is merely loud. The one thing it must
# never do is print a lie about provenance.
UNKNOWN = "unknown"


def git_describe():
    """`git describe --always --dirty`, or UNKNOWN if there is no git here.

    --always so a tree with no tags still names its commit; --dirty so a
    build from an edited tree says so in the one place a reader looks."""
    try:
        out = subprocess.run(
            ["git", "describe", "--always", "--dirty"],
            cwd=REPO, capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return UNKNOWN
    if out.returncode != 0:
        return UNKNOWN
    s = out.stdout.strip()
    return s if s else UNKNOWN


def stamp_text():
    # Minute resolution, not second: the stamp's job is to name a build,
    # and a reader comparing two boots wants "the same build" to LOOK the
    # same. Seconds would make every rebuild a different string and turn
    # the write-on-change guard into a write-every-time guard.
    when = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    return "%s %s" % (git_describe(), when)


BANNER = """\
// GENERATED by tools/build_stamp.py — do not edit, do not commit.
//
// PURSE_0 R2. This file lives in the BUILD directory, not the source
// tree: it carries a timestamp, so a tracked copy would dirty the tree on
// every build and turn the binding gate's S-6 witness permanently red.
// The tool's own banner carries the full reasoning.
//
// The git sha names the TREE; web_dist.py's __BUILD_ID__ names the
// ARTIFACT. The boot prints both, and the organ panel's status line
// echoes them together.
"""


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: build_stamp.py <output-path>\n")
        return 2
    out_path = sys.argv[1]
    text = BANNER + '\ninline constexpr const char* BUILD_STAMP = "%s";\n' % stamp_text()

    # WRITE ONLY ON CHANGE — the whole point of the always-run step being
    # cheap. A read that fails (first build, no file) is a change.
    try:
        with open(out_path, "r", encoding="utf-8") as fh:
            if fh.read() == text:
                return 0
    except OSError:
        pass

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
